# ========================================================================
# directory settings
# ========================================================================
site_dir: /
src_dir: src/
dist_dir: dist/
template_dir: config/templates/


# ========================================================================
# template settings
# ========================================================================
home_template: home.html
default_template: post.html


# ========================================================================
# link settings
# ========================================================================
link_prefix_format: "%Y-%m-%d-"
prev_next_links: true


# ========================================================================
# minification settings
# ========================================================================
output: dist/assets/
css:
  style:
    - src/css/*.css
javascript:
  script:
    - src/js/*.js


# ========================================================================
# formatting options
# ========================================================================
excerpt_length: 384
date_format: "%Y-%m-%d %H:%M"
code_line_numbers: true


# ========================================================================
# hipster settings (they don't fit in any category)
# ========================================================================
delimiter: "===========================================================================\n"
port: "3000"